import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { PageShell } from "@/components/marketplace/PageShell";
import { ResourceCard } from "@/components/marketplace/ResourceCard";
import { MarketplaceIcon } from "@/components/icons/MarketplaceIcons";
import { Button } from "@/components/ui/button";
import { BRANCHES, RESOURCES, SEMESTERS } from "@/data/mock";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Student Workspace — SGSITS Marketplace"},{name:"description",content:"Explore student-shared notes, PYQs and lab resources in the SGSITS Marketplace workspace."},{property:"og:title",content:"Student Workspace — SGSITS Marketplace"},{property:"og:description",content:"Notes, PYQs and study resources passed from one SGSITS student to another."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});
const tabs=[{label:"Everything",type:"all"},{label:"Notes",type:"Notes"},{label:"PYQs",type:"PYQ"},{label:"Handwritten",type:"Handwritten Notes"},{label:"Lab manuals",type:"Lab Manual"}];
function Home(){const[type,setType]=useState("all");const[branch,setBranch]=useState("all");const[semester,setSemester]=useState("all");const[sort,setSort]=useState("recent");const results=useMemo(()=>{const list=RESOURCES.filter(r=>(type==="all"||r.type===type)&&(branch==="all"||r.branch===branch)&&(semester==="all"||String(r.semester)===semester));return list.sort((a,b)=>sort==="downloads"?b.downloads-a.downloads:sort==="rating"?b.rating-a.rating:b.uploadedOn.localeCompare(a.uploadedOn));},[type,branch,semester,sort]);return <PageShell><div className="workspace-intro"><div><div className="intro-eyebrow"><span className="status-mark"/>FROM YOUR CAMPUS, FOR YOUR SEMESTER</div><h1>Student workspace<span className="title-period">.</span></h1><p>The good notes don’t stay in the group chat.</p></div><span className="demo-label">SAMPLE COLLECTION <span>↗</span></span></div><div className="resource-toolbar"><div className="resource-tabs" role="tablist" aria-label="Resource categories">{tabs.map(t=><Button key={t.type} role="tab" aria-selected={type===t.type} variant="ghost" onClick={()=>setType(t.type)} className={type===t.type?"resource-tab selected":"resource-tab"}>{t.label}</Button>)}</div><div className="workspace-selectors"><label><MarketplaceIcon name="branch" className="size-4"/><select aria-label="Branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All branches</option>{BRANCHES.map(b=><option key={b.code} value={b.code}>{b.code}</option>)}</select></label><label><MarketplaceIcon name="semester" className="size-4"/><select aria-label="Semester" value={semester} onChange={e=>setSemester(e.target.value)}><option value="all">All semesters</option>{SEMESTERS.map(s=><option key={s} value={s}>Semester {s}</option>)}</select></label></div></div><div className="collection-heading"><span><strong>{results.length}</strong> resources in the room</span><label>Sort by <select aria-label="Sort resources" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently added</option><option value="downloads">Most downloaded</option><option value="rating">Highest rated</option></select></label></div>{results.length?<div className="workspace-resource-grid">{results.map(r=><ResourceCard key={r.id} resource={r}/>)}</div>:<div className="workspace-empty"><MarketplaceIcon name="search" className="size-12"/><h2>Nothing here yet.</h2><p>Try another branch, semester, or resource type.</p><Button variant="outline" onClick={()=>{setType("all");setBranch("all");setSemester("all")}}>Clear filters</Button></div>}<div className="collection-end"><span>Knowledge moves. Keep it moving.</span><Link to="/upload">Share your notes <MarketplaceIcon name="arrow-right" className="size-4"/></Link></div></PageShell>}
