import { useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { CURRENT_USER } from "@/data/mock";
import { MarketplaceIcon, type IconName } from "@/components/icons/MarketplaceIcons";
import { MoodControl } from "@/components/brand/MoodControl";
import { Button } from "@/components/ui/button";
const links=[{to:"/",label:"Marketplace",icon:"browse"},{to:"/explore",label:"Explore resources",icon:"search"},{to:"/saved",label:"Saved collection",icon:"saved"},{to:"/my-uploads",label:"My uploads",icon:"notes"},{to:"/profile",label:"My profile",icon:"profile"}] as const;
export function Navbar(){const[open,setOpen]=useState(false);return <><div className="mobile-brand"><Link to="/" className="workspace-brand"><span className="brand-symbol"><MarketplaceIcon name="resource" className="size-6"/></span><span>SGSITS<span className="brand-subtitle">Marketplace</span></span></Link><Button variant="outline" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(!open)}><MarketplaceIcon name={open?"close":"menu"} className="size-5"/></Button></div><aside className={`workspace-sidebar ${open?"sidebar-open":""}`}><Link to="/" className="workspace-brand"><span className="brand-symbol"><MarketplaceIcon name="resource" className="size-6"/></span><span>SGSITS<span className="brand-subtitle">Marketplace</span></span></Link><p className="sidebar-tagline">The unofficial internet<br/>of SGSITS.</p><nav className="workspace-navigation"><p className="eyebrow">Your corner of campus</p>{links.map(l=><Link key={l.to} to={l.to} onClick={()=>setOpen(false)} className="sidebar-link" activeOptions={{exact:true}} activeProps={{className:"sidebar-link is-active"}}><MarketplaceIcon name={l.icon} className="size-5"/>{l.label}</Link>)}</nav><Link to="/upload" className="sidebar-upload"><MarketplaceIcon name="upload" className="size-5"/>Drop a resource<MarketplaceIcon name="arrow-right" className="ml-auto size-4"/></Link><MoodControl/><Link to="/profile" className="sidebar-user"><span className="user-avatar">{CURRENT_USER.initials}</span><span><strong>{CURRENT_USER.name}</strong><small>{CURRENT_USER.branch} · Semester {CURRENT_USER.semester}</small></span></Link><span className="sidebar-note">Student-built. Never official.</span></aside></>}
export function WorkspaceHeader(){const[q,setQ]=useState("");const navigate=useNavigate();return <header className="workspace-header"><form className="workspace-search" onSubmit={e=>{e.preventDefault();navigate({to:"/explore",search:{q}})}}><MarketplaceIcon name="search" className="size-5"/><input aria-label="Search all resources" placeholder="Search notes, subjects, or that one PYQ…" value={q} onChange={e=>setQ(e.target.value)}/><Button variant="ghost" type="submit" aria-label="Search"><MarketplaceIcon name="arrow-right" className="size-4"/></Button></form><Link to="/upload" className="header-upload"><MarketplaceIcon name="upload" className="size-4"/><span>Upload notes</span></Link><Link to="/login" className="header-login">Log in <MarketplaceIcon name="arrow-right" className="size-4"/></Link></header>}
export function MobileTabBar(){return <nav className="mobile-tab-bar">{[{to:"/",label:"Home",icon:"home"},{to:"/explore",label:"Explore",icon:"search"},{to:"/upload",label:"Upload",icon:"upload"},{to:"/saved",label:"Saved",icon:"saved"}].map(t=><Link key={t.to} to={t.to} activeOptions={{exact:true}} activeProps={{className:"is-active"}}><MarketplaceIcon name={t.icon as IconName} className="size-5"/>{t.label}</Link>)}</nav>}
