import { Link } from "@tanstack/react-router";
import type { Resource, ResourceType } from "@/data/types";
import { TYPE_LABELS } from "@/data/mock";
import { Rating } from "./Rating";
import { BookmarkButton } from "./BookmarkButton";
import { cn } from "@/lib/utils";
import { MarketplaceIcon, RESOURCE_ICON } from "@/components/icons/MarketplaceIcons";

const typeStyles: Record<ResourceType,string>={Notes:"bg-brand-soft text-brand", "Handwritten Notes":"bg-pink/15 text-pink", PYQ:"bg-sun/30 text-brand-deep", "Important Questions":"bg-signal/25 text-brand-deep", "Lab Manual":"bg-accent2/15 text-brand", Assignment:"bg-muted text-ink", "Study Guide":"bg-mint/20 text-brand-deep", Other:"bg-muted text-ink/70"};
export function TypePill({type,className}:{type:ResourceType;className?:string}){return <span className={cn("inline-flex items-center gap-1.5 rounded-sm px-2.5 py-1 text-[11px] font-bold",typeStyles[type],className)}><MarketplaceIcon name={RESOURCE_ICON[type]} className="size-3.5"/>{TYPE_LABELS[type]}</span>}
export function ResourceCard({resource}:{resource:Resource}){return <article className="glass glass-hover group relative overflow-hidden rounded-lg p-5"><span aria-hidden className="absolute inset-y-0 left-0 w-1 bg-brand opacity-75"/><div className="flex items-center justify-between"><TypePill type={resource.type}/><BookmarkButton resourceId={resource.id}/></div><Link to="/resource/$resourceId" params={{resourceId:resource.id}} className="mt-4 block"><h3 className="font-display text-[17px] font-bold leading-snug text-ink group-hover:text-brand">{resource.title}</h3><p className="mt-1.5 text-xs text-ink/55">{resource.subject} · {resource.branch} · Sem {resource.semester}</p></Link><div className="mt-5 flex items-center gap-2 border-t border-border pt-3"><span className="grid size-7 place-items-center rounded-md bg-brand-soft text-[10px] font-bold text-brand">{resource.uploader.initials}</span><span className="truncate text-xs font-semibold text-ink/70">{resource.uploader.name}</span><Rating value={resource.rating} className="ml-auto"/><span className="inline-flex items-center gap-1 text-[11px] text-ink/45"><MarketplaceIcon name="download" className="size-3.5"/>{resource.downloads}</span></div></article>}
